clear mex;
if ispc
    cd '..\c'
    if (~isempty(ver('MATLAB')))
                disp('compiling and linking under MATLAB');
                mex -DNDEBUG -DBUILD_MEX -DBUILD_MATLAB -DBUILD_LAPACK_H -DBUILD_BLAS_H -DBUILD_WIN32_GETTIMEOFDAY ...
                    -DKALMAN_STEP_INDEX_TYPE_INT64 -DFARRAY_INDEX_TYPE_INT64 -DPARALLEL_INDEX_TYPE_INT64 ...
                    ultimatekalmanmex.c ...
                    kalman_ultimate.c kalman_conventional.c kalman_oddeven_smoother.c kalman_associative_smoother.c ...
                    kalman_base.c kalman_explicit_representation.c ...
                    matrix_ops.c flexible_arrays.c concurrent_set.c parallel_sequential.c ...
                    -lmwlapack -lmwblas
    end
    if (~isempty(ver('Octave')))
        disp('compiling and linking under Octave ...');
        mkoctfile --mex -v -fmax-errors=5 ...
            -DNDEBUG ...
            -DBUILD_MEX ...
            -DBUILD_OCTAVE ...
            -DBUILD_BLAS_UNDERSCORE ...
            -DBUILD_BLAS_STRLEN_END ...
            ultimatekalmanmex.c ultimatekalman.c -llibopenblas -lliblapack
    end
    disp('compiling and linking done');
    cd '..\matlab'
    addpath '..\c'
end

if isunix
    cd '../c'
    if (~isempty(ver('MATLAB')))
        disp('compiling and linking under MATLAB ...');
        mex -DNDEBUG -DBUILD_MEX -DBUILD_MATLAB -DBUILD_LAPACK_H -DBUILD_BLAS_H ultimatekalmanmex.c ultimatekalman.c -lmwlapack -lmwblas
    end
    if (~isempty(ver('Octave')))
        disp('compiling and linking under Octave ...');
        mkoctfile --mex -v -fmax-errors=5 ...
            -DNDEBUG ...
            -DBUILD_MEX ...
            -DBUILD_OCTAVE ...
            -DBUILD_BLAS_UNDERSCORE ...
            -DBUILD_BLAS_STRLEN_END ...
            ultimatekalmanmex.c ultimatekalman.c -llibopenblas -lliblapack
    end
    disp('compiling and linking done');
    cd '../matlab'
    addpath '../c'
end

if ismac
    warning('MacOS mex generation not yet tested');
    cd '../c'
    if (~isempty(ver('MATLAB')))
        disp('compiling and linking under MATLAB ...');
        mex -DNDEBUG -DBUILD_MEX -DBUILD_MATLAB -DBUILD_LAPACK_H -DBUILD_BLAS_H ultimatekalmanmex.c ultimatekalman.c -lmwlapack -lmwblas
    end
    if (~isempty(ver('Octave')))
        disp('compiling and linking under Octave ...');
        mkoctfile --mex -v -fmax-errors=5 ...
            -DNDEBUG ...
            -DBUILD_MEX ...
            -DBUILD_OCTAVE ...
            -DBUILD_BLAS_UNDERSCORE ...
            -DBUILD_BLAS_STRLEN_END ...
            ultimatekalmanmex.c ultimatekalman.c -llibopenblas -lliblapack
    end
    disp('compiling and linking done');
    cd '../matlab'
    addpath '../c'
end


